config/routes.rb
Rails.application.routes.draw do
  resources :bookings, except: :index
  resources :flights, only: :index
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'flights#index'
end

app/models/airport.rb
# rubocop:disable Layout/HashAlignment
class Airport < ApplicationRecord
  has_many :departing_flights,
           class_name: 'Flight',
           foreign_key: 'departure_airport_id',
           inverse_of:  :departure_airport,
           dependent: :destroy
  has_many :arriving_flights,
           class_name: 'Flight',
           foreign_key: 'arrival_airport_id',
           inverse_of:  :arrival_airport,
           dependent: :destroy

  validates :code,
            presence: true,
            uniqueness: true,
            length: { is: 3 },
               format: { with: /\A[A-Z]{3}\z/ }
  validates :location, presence: true
end

# rubocop:enable Layout/HashAlignment

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight, inverse_of: :bookings, dependent: false
  has_many :passengers, dependent: :destroy, inverse_of: :booking
  accepts_nested_attributes_for :passengers, allow_destroy: true, limit: 4

  validate :passenger_count

  before_validation :passenger_removal

  validates_associated :passengers

  private

  def passenger_removal
    errors.add(:base, 'Must have at least one passenger') if passengers.reject(&:marked_for_destruction?).empty?
  end

  def passenger_count
    errors.add(:passengers, 'must be between 1 and 4') unless passengers.size.between?(1, 4)
  end
end

app/models/flight.rb
# rubocop:disable Layout/HashAlignment
class Flight < ApplicationRecord
  belongs_to :arrival_airport,
             class_name: 'Airport',
             inverse_of:  :arriving_flights,
             primary_key: :code
  belongs_to :departure_airport,
             class_name: 'Airport',
             inverse_of: :departing_flights,
             primary_key: :code
  has_many :bookings, dependent: :destroy, inverse_of: :flight

  validates :departure, :duration, presence: true
  validates :duration, numericality: { only_integer: true, greater_than: 3600, less_than: 86_400 }

  def pretty_departure
    departure.strftime('%m/%d/%Y')
  end

  def pretty_duration
    hours = duration / 3600
    minutes = (duration % 3600) / 60
    return "#{hours} hour" if minutes.zero?

    "#{hours} hour #{minutes} minutes"
  end

  def self.date_select_helper(flights)
    pretty_flights = departure_collection(flights)
    parse_flights(pretty_flights)
  end

  def self.departure_collection(flights)
    flights.map(&:pretty_departure).uniq
  end

  def self.departure_range(departure_date)
    start_range = Date.strptime(departure_date, '%m/%d/%Y').beginning_of_day
    (start_range..start_range + 1.day)
  end

  def self.parse_date_params(params) # rubocop:disable Metrics/AbcSize
    return nil if params.nil?

    params = params.compact_blank
    case params.keys.sort
    when %w[day month year]
      date = Date.new(params['year'].to_i, params['month'].to_i, params['day'].to_i)
      date..(date + 1.day - 0.1.seconds)
    when %w[month year]
      date = Date.new(params['year'].to_i, params['month'].to_i)
      date..(date + 1.month - 0.1.seconds)
    when ['year']
      date = Date.new(params['year'].to_i)
      date..(date + 1.year - 0.1.seconds)
    end
  end

  def self.parse_flights(flights)
    flights.each_with_object({ month: [], day: [], year: [] }) do |val, sum|
      m, d, y = val.split('/')
      sum[:month] << m
      sum[:day] << d
      sum[:year] << y
    end
    # flights.each do |_k, v|
    #   v&.uniq!
    #   v&.sort!
    # end
  end

  def pretty_arrival
    (departure + duration).strftime('%B %-d, %Y at %I:%M %p')
  end

  def pretty_departure_full
    departure.strftime('%B %-d, %Y at %I:%M %p')
  end
end

# rubocop:enable Layout/HashAlignment

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking, inverse_of: :passengers, dependent: false
  has_one :flight, through: :booking

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]
  before_action :build_booking, only: :new
  # after_action :mail_new_passengers, only: :create

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to flights_path, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_booking
    @booking = Booking.find(params[:id])
  end

  def build_booking
    params = booking_params
    booking = Booking.new(flight_id: params[:flight_id])
    params[:num_passengers].to_i.times { booking.passengers.build }
    @booking = booking
  end

  # Only allow a list of trusted parameters through.
  def booking_params
    params.require(:booking).permit(:flight_id, :num_passengers, :id, passengers_attributes: %i[id name email _destroy])
  end

  # def mail_new_passengers
  #   booking = @booking
  #   flight = booking.flight
  #   booking.passengers.each do |passenger|
  #     PassengersMailer.with(passenger:, flight:).new_passenger.deliver_later
  #   end
  # end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_current_search, only: %i[index]

  # GET /flights or /flights.json
  def index
    @airports = Airport.all
    @flights = execute_search
    @departures = Flight.date_select_helper(@flights)
  end

  private

  # Only allow a list of trusted parameters through.
  def flight_params
    params.permit(:arrival_airport, :departure_airport, :num_passengers, departure: %i[day month year]).compact_blank
  end

  def set_current_search
    search = flight_params
    departure_time = search[:departure]
    search[:departure] = Flight.parse_date_params(departure_time) if departure_time
    search[:departure_time] = departure_time
    @current_search = search
  end

  def execute_search
    search_params = @current_search.except(:departure_time, :num_passengers).compact
    return [] if search_params.empty?

    Flight.where(search_params)
      .order(:departure).includes(:arrival_airport, :departure_airport)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  def general_selector(form:, array:, field_name:, type:, current_value: {})
    current_value ||= {}
    form.select "#{field_name}[#{type}]",
                options_for_select(
                  array[type].uniq.sort || [],
                  selected: current_value && current_value[type]
                ),
                { include_blank: type.to_s.capitalize, selected: current_value[type] },
                { onchange: 'this.form.requestSubmit()' }
  end

  def date_select_fields(**kwargs)
    content_tag :div, class: 'date-select' do
      %i[year month day].map do |type|
        general_selector(type:, **kwargs)
      end.join.html_safe # rubocop:disable Rails/OutputSafety
    end
  end
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <div class="booking__flight"><%= render booking.flight %></div>
  <h2>Passengers:</h2>
  <%= render booking.passengers %>
</div>

app/views/bookings/_form.html.erb
<div class="booking-form">
  <%= form_with model: booking, id: 'booking-form' do |form| %>
    <%= form.hidden_field :flight_id %>
    <% if booking.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
        <ul>
          <% booking.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="booking__flight"><%= render 'flights/flight', flight: booking.flight %></div>
    <div class="passengers-list">
      <%= form.fields_for :passengers do |passenger_form| %>
        <div class="passengers-list__entry">
          <div class="passengers-list__input">
            <%= passenger_form.label :name, 'Name' %>
            <%= passenger_form.text_field :name %>
          </div>
          <div class="passengers-list__input">
            <%= passenger_form.label :email, 'Email' %>
            <%= passenger_form.text_field :email %>
          </div>
          <% unless booking.new_record? %>
            <div class="passengers-list__input passengers-list__input--small-text">
              <%= passenger_form.label :name, 'Remove?' %>
              <%= passenger_form.check_box :_destroy %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>
<%= render "form", booking: @booking %>
<%= submit_tag 'Update Booking', form:'booking-form', class: 'button button--left-aligned' %>
<br>
<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to flights", bookings_path %>
</div>

app/views/bookings/new.html.erb
<h1>New booking</h1>
<%= render "form", booking: @booking %>
<div class="booking-new__passenger_buttons">
  <% if @booking.passengers.size < 4 %>
    <%= form_with model: @booking, url: new_booking_path,  method: :get do |form| %>
      <%= form.hidden_field :flight_id %>
      <%= form.hidden_field :num_passengers, value: @booking.passengers.size + 1 %>
      <%= form.submit 'Add a passenger', class: 'button' %>
    <% end %>
  <% end %>
  <% if @booking.passengers.size > 1 %>
    <%= form_with model: @booking, url: new_booking_path,  method: :get do |form| %>
      <%= form.hidden_field :flight_id %>
      <%= form.hidden_field :num_passengers, value: @booking.passengers.size - 1 %>
      <%= form.submit 'Remove a passenger', class: 'button' %>
    <% end %>
  <% end %>
</div>
<%= submit_tag 'Create Booking', form:'booking-form', class: 'button button--left-aligned' %>
<div>
  <%= link_to "Back to flights", flights_path %>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @booking %>
<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= link_to "Back to flights", flights_path %>
  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>

app/views/flights/_flight.html.erb
<turbo-frame class="flight" id="<%= dom_id flight %>" loading="lazy">
  <div class="flight__airport">
    <strong>Flying from:</strong>
    <p><%= flight.departure_airport.location %></p>
    <p class="flight__time"><%= "Departing on #{flight.pretty_departure_full}" %></p>
  </div>
  <div class="flight__flight-duration">
    <div><%= inline_svg_tag 'right-arrow-alt.svg', class: 'flight__arrow' %></div>
    <p><%= flight.pretty_duration %></p>
  </div>
  <div class="flight__airport flight__airport--align-right">
    <strong>Flying to:</strong>
    <p><%= flight.arrival_airport.location %></p>
    <p class="flight__time"><%= "Arriving on #{flight.pretty_arrival}" %></p>
  </div>
</turbo-frame>

app/views/flights/_form.html.erb
<%= form_with(model: flight) do |form| %>
  <% if flight.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :arrival_airport, style: "display: block" %>
    <%= form.text_field :arrival_airport %>
  </div>

  <div>
    <%= form.label :departure_airport, style: "display: block" %>
    <%= form.text_field :departure_airport %>
  </div>

  <div>
    <%= form.label :departure, style: "display: block" %>
    <%= form.datetime_field :departure %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.time_field :duration %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/index.html.erb
<div class="">
  <p style="color: green"><%= notice %></p>
  <h1>Flights</h1>
  <%= form_with url: flights_path, method: :get, data_turbo_method: :get, class: 'flight-search-form' do |form| %>
    <div class="input">
      <%= form.label :num_passengers, 'Passengers' %>
      <%= form.select :num_passengers, options_for_select((1..4).to_a, selected: @current_search[:num_passengers]), { },  { onchange: "this.form.requestSubmit()", class: 'input__selector input__selector--small' } %>
    </div>
    <div class="input input--begins-row">
      <%= form.label :arrival_airport, 'Arrival Airport:' %>
      <%= form.collection_select :arrival_airport, @airports, :code, :location, { selected: @current_search[:arrival_airport], include_blank: 'None'}, { onchange: "this.form.requestSubmit()", class: 'input__selector' } %>
    </div>
    <div class="input">
      <%= form.label :departure_airport, 'Departure Airport:' %>
      <%= form.collection_select :departure_airport, @airports, :code, :location, { selected: @current_search[:departure_airport], include_blank: 'None'}, { onchange: "this.form.requestSubmit()", class: 'input__selector' } %>
    </div>
    <div class="input input--width-two">
      <span>Departure Date</span>
      <div class="input__selector">
        <%= date_select_fields(form:, array: @departures, field_name: 'departure', current_value: @current_search[:departure_time]) %>
      </div>
    </div>
    <%= form.submit 'Search', id: 'flight-submit', class: 'input--ends-row' %>
  <% end %>
  <%= turbo_frame_tag 'flights-list', class: 'flights' do %>
    <div class="flights-list">
      <% @flights.each do |flight| %>
        <div class="flights-list__selectable-flight">
          <%= render flight %>
          <%= form_with url: new_booking_path, scope: :booking, method: 'get', data_turbo_method: :get do |form| %>
            <%= form.hidden_field :flight_id, value: flight.id %>
            <%= form.hidden_field :num_passengers, value: @current_search[:num_passengers] %>
            <%= form.submit 'Select Flight', class: 'button'%>
          <% end %>
        </div>
      <% end  %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/passengers/_passenger.html.erb
<turbo-frame class="passenger" id="<%= dom_id passenger %>" loading="lazy">
  <div class="passenger__data"><span>Name:</span><span><%= passenger.name %></span></div>
  <div class="passenger__data"><span>Email:</span><span><%= passenger.email %></span></div>
</turbo-frame>